name: Java CD

on:
  release:
    types: [published]

jobs:
  publish:
    name: Publish mod

    steps:
      - uses: Kir-Antipov/mc-publish@v3.2
        with:
          # Modrinth
          modrinth-id: zG0Bb7gw
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          # CurseForge
          curseforge-id: 677580
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
